### ISSUE TITLE
BUG: Join Channel Allowance

### ISSUE THREAD

**Issue by sasicodes** [tapexyz/tape#1037]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Currently we show tooltip, says Update permission in Settings page.,

### Expected Behavior

Show popup to set allowance for super follow. 

### Steps To Reproduce

Try to super follow someone, with no allowance

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Chrome

**Comment by Sjjdud27** [comment]
جيد

**Comment by sasicodes** [comment]
We addressed this issue on upcoming v2 #1036 

Thanks for raising.
