### ISSUE TITLE
Profile image is cropped

### ISSUE THREAD

**Issue by aurosevic** [tapexyz/tape#1079]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When the menu opens after clicking on the profile picture in the top right corner of the site, the profile picture at the top of the opened menu is cropped.

![Screenshot_20231012_205922](https://github.com/tapexyz/tape/assets/19304661/dabc69f6-87ff-418e-bc99-1269f6c3ed81)

### Expected Behavior

Profile image inside the menu should be fully shown.

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Brave

**Comment by sasicodes** [comment]
Thanks @aurosevic for raising!

**Comment by aurosevic** [comment]
You're welcome! It's perfect now!
