### ISSUE TITLE
Wallet connect is not shown properly on mobile

### ISSUE THREAD

**Issue by aurosevic** [tapexyz/tape#1109]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When choosing Wallet connect on login screen on Safari mobile browser wallet options are not shown.
Here are the screen shots both in portrait and landscape.

Portrait:

![IMG_6689](https://github.com/tapexyz/tape/assets/19304661/f97594fb-2c01-420f-a47d-64a04c78ea13)

Landscape:

![IMG_6688](https://github.com/tapexyz/tape/assets/19304661/ed979dae-fff6-440e-a6d1-bfefc0d955a5)

### What platform(s) does this occur on?

Mobile

### What browser(s) does this occur on?

Safari

**Comment by sasicodes** [comment]
fixed in #1117
