### ISSUE TITLE
Ability to set NFT as Channel Avatar

### ISSUE THREAD

**Issue by sasicodes** [tapexyz/tape#22]
- Click the channel picture on the settings page (/settings) should open a modal with two tabs,
  - Choose from the computer
  - Choose from the collection
- Ability to crop the image after selecting.
- Differentiate NFT channel pictures from normal ones. (channel.picture?.__typename === 'NftImage')

**Comment by pabl0fb** [comment]
It would be great if we can support mainnet and some L2s.

**Comment by RamK777-stack** [comment]
working on this!
