### ISSUE TITLE
[Feature] Integration with Audius for Music Video channels like @millionrecords.lens

### ISSUE THREAD

**Issue by danimesq** [tapexyz/tape#408]
I'm open to discuss how this would work.

**Comment by danimesq** [comment]
Also suggested for Lenster, here: https://github.com/lensterxyz/lenster/issues/1315

**Comment by sasicodes** [comment]
May I know what you suggest that can be effectively implemented, Im open to chat around it! 🙇🏻

**Comment by danimesq** [comment]
> May I know what you suggest that can be effectively implemented, Im open to chat around it! 🙇🏻

Also open to chat about [USV](https://github.com/lenstube-xyz/lenstube/issues/409)?
